var botaoTodos=document.getElementById("btnNavTodas");var botaocasual=document.getElementById("btnNavCasual");var botaoginasta=document.getElementById("btnNavginasta");var botaomarvel=document.getElementById("btnNavmarvel");var botaolooney=document.getElementById("btnLooney");var mensagem_selecao=document.getElementById("mensagem_selecao");function verificarselecionado(){if(botaocasual.checked&&botaomarvel.checked&&botaolooney.checked&&botaoginasta.checked){botaoTodos.checked=!0}else if(botaocasual.checked==!1&&botaomarvel.checked==!1&&botaolooney.checked==!1&&botaoginasta.checked==!1){mensagem_selecao.innerHTML="Selecione alguma coleção!"}}
var peca_home=document.getElementsByClassName("peca_home");botaoTodos.addEventListener("click",()=>{if(botaoTodos.checked){for(let item of peca_home){item.style.display="block"};botaocasual.checked=!0;botaomarvel.checked=!0;botaolooney.checked=!0;botaoginasta.checked=!0;mensagem_selecao.innerHTML="Peças"}else{for(let item of peca_home){item.style.display="none"};botaocasual.checked=!1;botaomarvel.checked=!1;botaolooney.checked=!1;botaoginasta.checked=!1;mensagem_selecao.innerHTML="Selecione alguma coleção!"}});botaocasual.addEventListener("click",()=>{var colecao_casual=document.getElementsByClassName("colecao_casual");if(botaocasual.checked){for(let item of colecao_casual){item.style.display="block";mensagem_selecao.innerHTML="Peças"}}else{for(let item of colecao_casual){item.style.display="none"}
botaoTodos.checked=!1}
verificarselecionado()});botaoginasta.addEventListener("click",()=>{var colecao_ginasta=document.getElementsByClassName("colecao_ginasta");if(botaoginasta.checked){for(let item of colecao_ginasta){item.style.display="block";mensagem_selecao.innerHTML="Peças"}}else{for(let item of colecao_ginasta){item.style.display="none"}
botaoTodos.checked=!1}
verificarselecionado()});botaomarvel.addEventListener("click",()=>{var colecao_marvel=document.getElementsByClassName("colecao_marvel");if(botaomarvel.checked){for(let item of colecao_marvel){item.style.display="block";mensagem_selecao.innerHTML="Peças"}}else{for(let item of colecao_marvel){item.style.display="none"}
botaoTodos.checked=!1}
verificarselecionado()});botaolooney.addEventListener("click",()=>{var colecao_looney=document.getElementsByClassName("colecao_Looney");if(botaolooney.checked){for(let item of colecao_looney){item.style.display="block";mensagem_selecao.innerHTML="Peças"}}else{for(let item of colecao_looney){item.style.display="none"}
botaoTodos.checked=!1}
verificarselecionado()});var checkbox_pecas=document.getElementsByClassName("checkbox_pecas");var numeroitenscarrinho=document.getElementById("numeroitenscarrinho");var preco_peca=document.getElementsByClassName("preco_individual_peca");let valornumeroitenscarrinho=0;let valortotalitens=0;for(let checkbox of checkbox_pecas){checkbox.addEventListener("click",()=>{if(checkbox.checked){valortotalitens=valortotalitens+parseInt(checkbox.value);valornumeroitenscarrinho=valornumeroitenscarrinho+1}else{valortotalitens=valortotalitens-parseInt(checkbox.value);valornumeroitenscarrinho=valornumeroitenscarrinho-1}
console.log(valortotalitens);numeroitenscarrinho.innerHTML=valornumeroitenscarrinho})}
var pecas_home_container=document.getElementById("pecas_home_container");pecas_home_container.addEventListener("submit",(event)=>{if(valornumeroitenscarrinho>0){sessionStorage.setItem("valortotal",valortotalitens);sessionStorage.setItem("numeroitens",valornumeroitenscarrinho)}else{alert("Você ainda não adicionou nenhum item no carrinho.");event.preventDefault()}});var main=document.querySelector("main");var container_peca_aberta=document.getElementById("container_peca_aberta");var numimagem=1;for(let peca of peca_home){peca.addEventListener("click",(event)=>{if(avaliar_atendimento.style.display!="block"&&caixa_login.style.display=="none"){if(event.target===peca){numimagem=1;container_peca_aberta.style.backgroundImage=peca.style.backgroundImage;container_peca_aberta.style.display="flex";main.style.filter="blur(0.5rem)";main.style.overflowY='hidden'}}else{container_peca_aberta.style.display='none'}})}
document.getElementById("botaofecharpecaaberta").addEventListener("click",()=>{container_peca_aberta.style.display="none";main.style.filter="blur(0rem)";main.style.overflowY='auto'});var botaoproximaimagem=document.getElementById("botaoproximaimagem");botaoproximaimagem.addEventListener("click",()=>{if(numimagem==1){numimagem=2}else{numimagem=1}
container_peca_aberta.style.backgroundImage=container_peca_aberta.style.backgroundImage.substring(0,18)+numimagem+container_peca_aberta.style.backgroundImage.substring(19,27)});botaovoltarimagem.addEventListener("click",()=>{if(numimagem==1){numimagem=2}else{numimagem=1}
container_peca_aberta.style.backgroundImage=container_peca_aberta.style.backgroundImage.substring(0,18)+numimagem+container_peca_aberta.style.backgroundImage.substring(19,27)})